skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
agentic_rwa_modern = "39CDc5zXBMFkjqZoELL4bYr9VrMNZCk1e9tzGnrgmdpz"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
